export const container = 
{
    width: '100%',
    margin:'auto',
    maxWidth: '300px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '2rem',
    borderRadius: '1rem',
    backgroundColor: 'hsl(0, 0%, 100%)',
    border: '4px solid hsl(0, 0%, 90%)',
    boxShadow: 'rgba(0, 0, 0, 0.24) 0px 3px 8px',
    color: 'black',
}
export const button= {
    alignSelf: 'center',
    appearance: 'none',
    backgroundColor: 'transparent',
    border:' 2px solid #1A1A1A',
    borderRadius: '15px',
    boxSizing: 'border-box',
    color: '#3B3B3B',
    cursor: 'pointer',
    display:' inline-block',
    fontFamily:' Roobert,-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"',
    fontSize: '16px',
    fontWeight: '600',
    lineHeight: 'normal',
    margin: '0',
    height: '60px',
    minWidth: '0',
    outline: 'none',
    padding: '16px 24px',
    textAlign: 'center',
    textDecoration: 'none',
    transition: 'all 300ms cubic-bezier(.23, 1, 0.32, 1)',
    userSelect: 'none',
    maxWidth:'150px',
    willChange: 'transform',
  }
